name: CI Quality Lab
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # optional: you could add a service (like postgres) here
      docker:
        image: docker:20.10.16
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and test with Maven
        run: mvn -B -f backend/pom.xml clean verify
      - name: Run Newman (Postman tests)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Newman CLI
        run: |
          npm install -g newman
          newman run tests/postman/QualityLab.postman_collection.json || true
      - name: Upload JaCoCo report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: backend/target/site/jacoco
